Document: redking
Title: Debian redking Manual
Author: <insert document author here>
Abstract: This manual describes what redking is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/redking/redking.sgml.gz

Format: postscript
Files: /usr/share/doc/redking/redking.ps.gz

Format: text
Files: /usr/share/doc/redking/redking.text.gz

Format: HTML
Index: /usr/share/doc/redking/html/index.html
Files: /usr/share/doc/redking/html/*.html
