# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_redking', [dirname(__file__)])
        except ImportError:
            import _redking
            return _redking
        if fp is not None:
            try:
                _mod = imp.load_module('_redking', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _redking = swig_import_helper()
    del swig_import_helper
else:
    import _redking
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, model, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _redking.new_model()
        try: self.this.append(this)
        except: self.this = this
    def init(self): return _redking.model_init(self)
    def step(self): return _redking.model_step(self)
    def set_model(self, *args): return _redking.model_set_model(self, *args)
    def get_hosts(self): return _redking.model_get_hosts(self)
    def get_parasites(self): return _redking.model_get_parasites(self)
    def get_host_cost(self): return _redking.model_get_host_cost(self)
    def get_parasite_cost(self): return _redking.model_get_parasite_cost(self)
    def get_matrix(self): return _redking.model_get_matrix(self)
    __swig_setmethods__["m_cost_params"] = _redking.model_m_cost_params_set
    __swig_getmethods__["m_cost_params"] = _redking.model_m_cost_params_get
    if _newclass:m_cost_params = _swig_property(_redking.model_m_cost_params_get, _redking.model_m_cost_params_set)
    def update_cost_functions(self): return _redking.model_update_cost_functions(self)
    __swig_destroy__ = _redking.delete_model
    __del__ = lambda self : None;
model_swigregister = _redking.model_swigregister
model_swigregister(model)


def new_rk_real(*args):
  return _redking.new_rk_real(*args)
new_rk_real = _redking.new_rk_real

def delete_rk_real(*args):
  return _redking.delete_rk_real(*args)
delete_rk_real = _redking.delete_rk_real

def rk_real_getitem(*args):
  return _redking.rk_real_getitem(*args)
rk_real_getitem = _redking.rk_real_getitem

def rk_real_setitem(*args):
  return _redking.rk_real_setitem(*args)
rk_real_setitem = _redking.rk_real_setitem
class rk_realp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rk_realp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rk_realp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _redking.new_rk_realp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _redking.delete_rk_realp
    __del__ = lambda self : None;
    def assign(self, *args): return _redking.rk_realp_assign(self, *args)
    def value(self): return _redking.rk_realp_value(self)
    def cast(self): return _redking.rk_realp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _redking.rk_realp_frompointer
    if _newclass:frompointer = staticmethod(_redking.rk_realp_frompointer)
rk_realp_swigregister = _redking.rk_realp_swigregister
rk_realp_swigregister(rk_realp)

def rk_realp_frompointer(*args):
  return _redking.rk_realp_frompointer(*args)
rk_realp_frompointer = _redking.rk_realp_frompointer

# This file is compatible with both classic and new-style classes.


